version: '3.8'

services:
    postgres:
        container_name: postgres
        image: postgres:12.8
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=testdb
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
    #      - ./postgres-data:/var/lib/postgresql/data
    #      # copy the sql script to create tables
          - ./scripts/scriptdb.sql:/docker-entrypoint-initdb.d/create_tables.sql
    web:
        container_name: webb
       build:
            context: .
            dockerfile: ./build/endpoint/Dockerfile
        ports:
            - "8080:8080"
        restart: unless-stopped
        expose:
            - "8080"
        depends_on:
            - postgres
    messagebroker:
        image: rabbitmq:management
        container_name: message-broke
        ports:
            - "5672:5672" # for sender and consumer connections
            - "15672:15672" # for serve RabbitMQ GUI
        restart: always
    workerapp:
        container_name: worker
        build:
            context: .
            dockerfile: ./build/worker/Dockerfile
        restart: unless-stopped
        depends_on:
            - messagebroker

