apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: messagebroker
  name: messagebroker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messagebroker
  strategy: {}
  template:
    metadata:
      labels:
        app: messagebroker
    spec:
      containers:
        - image: rabbitmq:management
          name: message-broke
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources: {}
      restartPolicy: Always
status: {}
