apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workerapp
  name: workerapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workerapp
  strategy: {}
  template:
    metadata:
      labels:
        app: workerapp
    spec:
      containers:
        - image: workerapp
          name: worker
          resources: {}
      restartPolicy: Always
status: {}
