apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-config
data:
  mq_host: amqp
  mq_port: "5672"
  mq_name: messagebroker
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  db_host: postgres
  db_port: "5432"
  db_name: testdb
