apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint
spec:
  selector:
    matchLabels:
      app: endpoint
  replicas: 1
  template:
    metadata:
      labels:
        app: endpoint
    spec:
      containers:
      - name: endpoint
        image: jainor/challenge:1.2
        env: 
        - name: mq_host
          value: amqp
        - name: mq_port
          value: "5672"
        - name: mq_user
          value: guest
        - name: mq_password
          value: guest
        - name: name
          value: messagebroker
        ports:
        - containerPort: 8080
