apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
type: Opaque
data:
    db_user: cG9zdGdyZXM=
    db_password: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
    name: rabbitmq-secrets
type: Opaque
data:
    mq_user: Z3Vlc3Q=
    mq_password: Z3Vlc3Q=
